# Generated by Django 3.2.7 on 2021-10-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_author_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_category',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
